#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';

const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'tracekeeper-activity-workflow-diagnostics-test-'));
const output = path.join(tempRoot, 'activity-workflow-diagnostics.test.mjs');

try {
	await build({
		entryPoints: [path.resolve('src/features/activity/activity-workflow-diagnostics.ts')],
		outfile: output,
		bundle: true,
		platform: 'node',
		format: 'esm',
		logLevel: 'silent',
	});

	const diagnosticsModule = await import(`${pathToFileURL(output).href}?test=${Date.now()}`);

	const now = 1700000000000;
	const events = [
		{
			path: 'audit/1.md',
			auditId: 'a1',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: '',
			taskId: 'task-a',
			timestamp: new Date(now - 900000).toISOString(),
			sortTimestamp: now - 900000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'alpha',
			agentId: 'alpha',
			sessionId: 's1',
			clientName: 'obsidian',
			toolName: 'tracekeeper.start_task',
			resultStatus: 'success',
			targetPaths: [],
			durationMs: '100',
			riskLevel: 'low',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-a',
			recallId: '',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '',
			memoryCloseoutStatus: '',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/2.md',
			auditId: 'a2',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: '',
			taskId: 'task-a',
			timestamp: new Date(now - 800000).toISOString(),
			sortTimestamp: now - 800000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'alpha',
			agentId: 'alpha',
			sessionId: 's1',
			clientName: 'obsidian',
			toolName: 'tracekeeper.recall',
			resultStatus: 'success',
			targetPaths: [],
			durationMs: '50',
			riskLevel: 'low',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-a',
			recallId: 'rec-a',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '0',
			memoryCloseoutStatus: '',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/3.md',
			auditId: 'a3',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: '',
			taskId: 'task-a',
			timestamp: new Date(now - 700000).toISOString(),
			sortTimestamp: now - 700000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'alpha',
			agentId: 'alpha',
			sessionId: 's1',
			clientName: 'obsidian',
			toolName: 'tracekeeper.read_note',
			resultStatus: 'success',
			targetPaths: [],
			durationMs: '20',
			riskLevel: 'low',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-a',
			recallId: 'rec-a',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '',
			memoryCloseoutStatus: '',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/4.md',
			auditId: 'a4',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: '',
			taskId: 'task-a',
			timestamp: new Date(now - 600000).toISOString(),
			sortTimestamp: now - 600000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'alpha',
			agentId: 'alpha',
			sessionId: 's1',
			clientName: 'obsidian',
			toolName: 'tracekeeper.finish_task',
			resultStatus: 'success',
			targetPaths: [],
			durationMs: '10',
			riskLevel: 'low',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-a',
			recallId: 'rec-a',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '',
			memoryCloseoutStatus: 'recorded',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/5.md',
			auditId: 'a5',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: '',
			taskId: 'task-b',
			timestamp: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
			sortTimestamp: now - 26 * 60 * 60 * 1000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'beta',
			agentId: 'beta',
			sessionId: 's2',
			clientName: 'obsidian',
			toolName: 'tracekeeper.start_task',
			resultStatus: 'success',
			targetPaths: [],
			durationMs: '30',
			riskLevel: 'low',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-b',
			recallId: '',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '',
			memoryCloseoutStatus: '',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/6.md',
			auditId: 'a6',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: 'permission denied',
			taskId: 'task-b',
			timestamp: new Date(now - 25 * 60 * 60 * 1000).toISOString(),
			sortTimestamp: now - 25 * 60 * 60 * 1000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'beta',
			agentId: 'beta',
			sessionId: 's2',
			clientName: 'obsidian',
			toolName: 'tracekeeper.recall',
			resultStatus: 'failed',
			targetPaths: [],
			durationMs: '40',
			riskLevel: 'high',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-b',
			recallId: 'rec-b',
			actionId: '',
			actionReasonCode: 'permission_denied',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '3',
			memoryCloseoutStatus: '',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/7.md',
			auditId: 'a7',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: 'permission denied',
			taskId: 'task-c',
			timestamp: new Date(now - 180000).toISOString(),
			sortTimestamp: now - 180000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'gamma',
			agentId: 'gamma',
			sessionId: 's3',
			clientName: 'obsidian',
			toolName: 'tracekeeper.start_task',
			resultStatus: 'success',
			targetPaths: [],
			durationMs: '15',
			riskLevel: 'low',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-c',
			recallId: '',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '',
			memoryCloseoutStatus: '',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/8.md',
			auditId: 'a8',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: '',
			taskId: 'task-c',
			timestamp: new Date(now - 120000).toISOString(),
			sortTimestamp: now - 120000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'gamma',
			agentId: 'gamma',
			sessionId: 's3',
			clientName: 'obsidian',
			toolName: 'tracekeeper.read_note',
			resultStatus: 'success',
			targetPaths: [],
			durationMs: '20',
			riskLevel: 'low',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-c',
			recallId: 'rec-c',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '2',
			memoryCloseoutStatus: '',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
		{
			path: 'audit/9.md',
			auditId: 'a9',
			actor: 'a',
			action: 'tool-call',
			target: '',
			reason: '',
			taskId: 'task-c',
			timestamp: new Date(now - 60000).toISOString(),
			sortTimestamp: now - 60000,
			snippet: '',
			eventType: 'tool-call',
			principalId: 'gamma',
			agentId: 'gamma',
			sessionId: 's3',
			clientName: 'obsidian',
			toolName: 'tracekeeper.finish_task',
			resultStatus: 'failed',
			targetPaths: [],
			durationMs: '25',
			riskLevel: 'high',
			argsSummary: '',
			resultSummary: '',
			workflowContractVersion: '',
			resultSchemaVersion: '',
			workflowMode: 'tracked_task',
			workflowId: 'task-c',
			recallId: 'rec-c',
			actionId: '',
			actionReasonCode: '',
			snapshotGeneration: '',
			scopeMode: '',
			scopeConfidence: '',
			matchedCount: '',
			memoryCloseoutStatus: 'failed',
			transport: 'streamable-http',
			runtimeVersion: '1',
		},
	];

	const diagnostics = diagnosticsModule.buildAgentWorkflowDiagnostics(events, now);
	assert.equal(diagnostics.activeWorkflowCount, 2);
	assert.equal(diagnostics.agedWorkflowCount, 1);
	assert.equal(diagnostics.successfulStartCount, 3);
	assert.equal(diagnostics.successfulRecallCount, 1);
	assert.equal(diagnostics.startToRecallCount, 1);
	assert.equal(diagnostics.recallToReadCount, 1);
	assert.equal(diagnostics.startToFinishCount, 1);
	assert.equal(diagnostics.permissionDeniedCount, 1);
	assert.equal(diagnostics.zeroMatchRecallCount, 1);
	assert.deepEqual(diagnostics.closeoutStatusDistribution, {
		recorded: 1,
		failed: 1,
	});
	assert.equal(diagnostics.durationP50Ms, 25);
	assert.equal(diagnostics.durationP95Ms, 100);
	assert.deepEqual(diagnostics.recentPrincipals, ['gamma', 'alpha', 'beta']);

	assert.equal(diagnosticsModule.buildAgentWorkflowDiagnosticsTestHelpers.parseNumeric('42'), 42);
	assert.equal(diagnosticsModule.buildAgentWorkflowDiagnosticsTestHelpers.parseNumeric('abc'), null);
	assert.equal(diagnosticsModule.buildAgentWorkflowDiagnosticsTestHelpers.percentile([30, 10, 20], 0.5), 20);

	const duplicateStart = { ...events[0], auditId: 'a1-replay', sortTimestamp: events[0].sortTimestamp + 1 };
	const replayDiagnostics = diagnosticsModule.buildAgentWorkflowDiagnostics([...events, duplicateStart], now);
	assert.equal(replayDiagnostics.successfulStartCount, 3);
	const wrongRecallRead = events.map((event) => event.auditId === 'a3' ? { ...event, recallId: 'rec-other' } : event);
	assert.equal(diagnosticsModule.buildAgentWorkflowDiagnostics(wrongRecallRead, now).recallToReadCount, 0);

	process.stdout.write(`${JSON.stringify({ result: 'pass', checks: 16 })}\n`);
} finally {
	fs.rmSync(tempRoot, { recursive: true, force: true });
}
