#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';

const tempRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'tracekeeper-onboarding-acceptance-'));

try {
	const stateBundle = path.join(tempRoot, 'onboarding-state.bundle.mjs');
	const viewModelBundle = path.join(tempRoot, 'onboarding-view-model.bundle.mjs');
	const pluginBundle = path.join(tempRoot, 'main.bundle.mjs');
	const embeddedBundleOutput = path.join(tempRoot, 'skill-bundle.mjs');
	await build({ entryPoints: [path.resolve('src/features/onboarding/onboarding-state.ts')], outfile: stateBundle, bundle: true, platform: 'node', format: 'esm', logLevel: 'silent' });
	await build({ entryPoints: [path.resolve('src/features/onboarding/onboarding-view-model.ts')], outfile: viewModelBundle, bundle: true, platform: 'node', format: 'esm', logLevel: 'silent' });
	await build({
		entryPoints: [path.resolve('src/main.ts')],
		outfile: pluginBundle,
		bundle: true,
		platform: 'node',
		format: 'esm',
		target: ['es2018'],
		external: ['obsidian'],
		logLevel: 'silent',
		loader: { '.md': 'text', '.json': 'text' },
	});
	await build({
		entryPoints: [path.resolve('src/features/skill-installation/skill-bundle.ts')],
		outfile: embeddedBundleOutput,
		bundle: true,
		platform: 'node',
		format: 'esm',
		logLevel: 'silent',
		loader: { '.md': 'text', '.json': 'text' },
	});

	const onboardingState = await import(`${pathToFileURL(stateBundle).href}?test=${Date.now()}`);
	const onboardingViewModel = await import(`${pathToFileURL(viewModelBundle).href}?test=${Date.now()}`);
	const embeddedBundle = await import(`${pathToFileURL(embeddedBundleOutput).href}?test=${Date.now()}`);
	const settingsSource = fs.readFileSync('src/features/settings/tracekeeper-setting-tab.ts', 'utf8');
	const buildSource = fs.readFileSync('scripts/build.mjs', 'utf8');
	const skillBundleSource = fs.readFileSync('src/features/skill-installation/skill-bundle.ts', 'utf8');
	const pluginBundleSource = fs.readFileSync(pluginBundle, 'utf8');

	assert.equal(onboardingState.ONBOARDING_STEP_SEQUENCE[3], 'skill_setup');
	assert.equal(onboardingState.ONBOARDING_STEP_SEQUENCE[4], 'agent_restart');
	const migrated = onboardingState.normalizeOnboardingSettingsState({
		selectedClientId: 'codex',
		skillSetupCompletedAt: '2026-07-22T00:00:00.000Z',
	});
	assert.equal(migrated.skillUserConfirmedAt, '2026-07-22T00:00:00.000Z');
	assert.equal(migrated.skillFileVerifiedAt, '');

	const evidenceState = {
		...migrated,
		skillUserConfirmedAt: '',
		skillSetupCompletedAt: '',
		agentRestartCompletedAt: '2026-07-22T00:00:01.000Z',
		connectionVerifiedAt: '2026-07-22T00:00:02.000Z',
		firstRecallCompletedAt: '2026-07-22T00:00:03.000Z',
		firstRecallMatchedCount: 2,
	};
	const context = onboardingViewModel.buildOnboardingContext({
		vaultReady: true,
		runtimeState: 'running',
		runtimeEnabled: true,
		selectedClient: { clientId: 'codex', configState: 'configured' },
		skillInstallState: { state: 'installed', fileVerified: true, updateAvailable: false },
		onboarding: evidenceState,
	});
	assert.equal(context.skillFileVerified, true);
	assert.equal(context.skillUserConfirmed, false);
	assert.equal(context.recallObserved, true);
	assert.equal(context.trackedWorkflowObserved, false);
	assert.equal(onboardingState.getNextOnboardingStep(evidenceState, context), 'complete');

	assert.ok(buildSource.includes('checkTracekeeperSkillBundle'));
	assert.ok(buildSource.includes("'.json': 'text'"));
	assert.ok(skillBundleSource.includes('references/workflow-state-machine.md'));
	assert.ok(skillBundleSource.includes('references/ingestion-workflow.md'));
	assert.ok(skillBundleSource.includes('references/failure-recovery.md'));
	assert.ok(skillBundleSource.includes('references/closeout-fields.md'));
	assert.ok(skillBundleSource.includes('references/instruction-isolation.md'));
	assert.ok(skillBundleSource.includes('dist/tracekeeper.flattened.md'));
	assert.ok(skillBundleSource.includes('manifest.json'));
	assert.equal(/skills\/tracekeeper\/SKILL\.md['"]/.test(settingsSource), false);
	assert.ok(settingsSource.includes('SkillInstallPreviewModal'));
	assert.ok(settingsSource.includes('not file verification'));
	assert.ok(settingsSource.includes('Does not prove automatic Skill triggering'));
	assert.ok(settingsSource.includes('Local single-user default profile (not team RBAC)'));

	assert.ok(pluginBundleSource.includes('tracekeeper-skill-bundle-v'));
	assert.ok(pluginBundleSource.includes('"format_version": 1'));
	assert.ok(pluginBundleSource.includes('Workflow State Machine'));
	assert.ok(pluginBundleSource.includes('Multi-source Ingestion Workflow'));
	assert.ok(pluginBundleSource.includes('Failure Recovery'));
	assert.ok(pluginBundleSource.includes('Instruction Isolation'));
	assert.ok(pluginBundleSource.includes('Generated by scripts/build_tracekeeper_skill.mjs'));
	assert.ok(pluginBundleSource.includes('skill_version'));
	assert.ok(pluginBundleSource.includes('2.1.0'));
	assert.ok(pluginBundleSource.includes('if_context_insufficient'));
	assert.ok(pluginBundleSource.includes('at_task_closeout'));
	for (const content of Object.values(embeddedBundle.TRACEKEEPER_SKILL_BUNDLE.installFiles)) {
		assert.equal(/(?:sk-[A-Za-z0-9_-]{12,}|api_key\s*[:=]\s*[A-Za-z0-9._-]{12,})/i.test(content), false);
	}

	process.stdout.write(`${JSON.stringify({ result: 'pass', checks: 29 })}\n`);
} finally {
	fs.rmSync(tempRoot, { recursive: true, force: true });
}
