import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

export const TRACEKEEPER_SKILL_FORMAT_VERSION = 1;
export const TRACEKEEPER_SKILL_SOURCE_FILES = Object.freeze([
	'SKILL.md',
	'references/workflow-state-machine.md',
	'references/failure-recovery.md',
	'references/closeout-fields.md',
	'references/instruction-isolation.md',
]);
export const TRACEKEEPER_SKILL_MANIFEST_PATH = 'manifest.json';
export const TRACEKEEPER_SKILL_FLATTENED_PATH = 'dist/tracekeeper.flattened.md';

export function normalizeTracekeeperSkillText(value) {
	const withoutBom = value.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n');
	return `${withoutBom.trimEnd()}\n`;
}

function sha256(value) {
	return `sha256:${createHash('sha256').update(value, 'utf8').digest('hex')}`;
}

function buildFlattenedArtifact(sources) {
	const [entrypoint, ...references] = sources;
	const referenceAnchors = new Map(references.map(({ relativePath, content }) => {
		const heading = content.match(/^#\s+(.+)$/m)?.[1] ?? path.basename(relativePath, '.md');
		const anchor = heading
			.toLowerCase()
			.replace(/[^a-z0-9\s-]/g, '')
			.trim()
			.replace(/\s+/g, '-');
		return [relativePath, `#${anchor}`];
	}));
	const flattenedEntrypoint = entrypoint.content.replace(
		/\[([^\]]+)\]\((references\/[^)]+\.md)\)/g,
		(match, label, relativePath) => referenceAnchors.has(relativePath)
			? `[${label}](${referenceAnchors.get(relativePath)})`
			: match,
	);
	const sections = references.map(({ relativePath, content }) => (
		`\n---\n\n<!-- tracekeeper-source: ${relativePath} -->\n\n${content.trimEnd()}\n`
	));
	return normalizeTracekeeperSkillText(
		`${flattenedEntrypoint.trimEnd()}\n\n<!-- Generated by scripts/build_tracekeeper_skill.mjs. Do not edit this compatibility artifact. -->\n${sections.join('')}`
	);
}

export async function buildTracekeeperSkillBundle(repoRoot = process.cwd()) {
	const skillRoot = path.join(repoRoot, 'skills', 'tracekeeper');
	const sources = [];

	for (const relativePath of TRACEKEEPER_SKILL_SOURCE_FILES) {
		const content = normalizeTracekeeperSkillText(
			await readFile(path.join(skillRoot, ...relativePath.split('/')), 'utf8')
		);
		sources.push({ relativePath, content, sha256: sha256(content) });
	}

	const canonicalBundle = [
		`tracekeeper-skill-bundle-v${TRACEKEEPER_SKILL_FORMAT_VERSION}`,
		...sources.map(({ relativePath, sha256: sourceHash }) => `${relativePath}\0${sourceHash}`),
		'',
	].join('\n');
	const flattened = buildFlattenedArtifact(sources);
	const manifest = {
		format_version: TRACEKEEPER_SKILL_FORMAT_VERSION,
		name: 'tracekeeper',
		skill_version: '2.0.0',
		workflow_contract_version: 2,
		minimum_tracekeeper_version: '0.2.3',
		hash_algorithm: 'sha256',
		bundle_hash: sha256(canonicalBundle),
		files: sources.map(({ relativePath, sha256: sourceHash }) => ({
			path: relativePath,
			sha256: sourceHash,
		})),
		artifacts: {
			flattened: {
				path: TRACEKEEPER_SKILL_FLATTENED_PATH,
				sha256: sha256(flattened),
			},
		},
	};

	return {
		manifest,
		manifestText: `${JSON.stringify(manifest, null, 2)}\n`,
		flattened,
	};
}

export async function writeTracekeeperSkillBundle(repoRoot = process.cwd()) {
	const skillRoot = path.join(repoRoot, 'skills', 'tracekeeper');
	const built = await buildTracekeeperSkillBundle(repoRoot);
	await mkdir(path.join(skillRoot, 'dist'), { recursive: true });
	await writeFile(path.join(skillRoot, TRACEKEEPER_SKILL_FLATTENED_PATH), built.flattened, 'utf8');
	await writeFile(path.join(skillRoot, TRACEKEEPER_SKILL_MANIFEST_PATH), built.manifestText, 'utf8');
	return built;
}

export async function checkTracekeeperSkillBundle(repoRoot = process.cwd()) {
	const skillRoot = path.join(repoRoot, 'skills', 'tracekeeper');
	const built = await buildTracekeeperSkillBundle(repoRoot);
	const errors = [];
	for (const [relativePath, expected] of [
		[TRACEKEEPER_SKILL_MANIFEST_PATH, built.manifestText],
		[TRACEKEEPER_SKILL_FLATTENED_PATH, built.flattened],
	]) {
		let actual;
		try {
			actual = await readFile(path.join(skillRoot, ...relativePath.split('/')), 'utf8');
		} catch {
			errors.push(`missing generated Skill artifact: ${relativePath}`);
			continue;
		}
		if (actual !== expected) {
			errors.push(`stale generated Skill artifact: ${relativePath}`);
		}
	}
	return errors;
}

async function main() {
	const args = process.argv.slice(2);
	const checkOnly = args.includes('--check');
	const rootIndex = args.indexOf('--root');
	const repoRoot = rootIndex >= 0 ? path.resolve(args[rootIndex + 1]) : process.cwd();
	if (rootIndex >= 0 && !args[rootIndex + 1]) {
		throw new Error('--root requires a path');
	}

	if (checkOnly) {
		const errors = await checkTracekeeperSkillBundle(repoRoot);
		if (errors.length > 0) {
			for (const error of errors) console.error(`ERROR: ${error}`);
			process.exitCode = 1;
			return;
		}
		console.log('Tracekeeper Skill bundle is current.');
		return;
	}

	await writeTracekeeperSkillBundle(repoRoot);
	console.log('Generated Tracekeeper Skill manifest and flattened compatibility artifact.');
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (invokedPath === import.meta.url) {
	main().catch((error) => {
		console.error(error instanceof Error ? error.message : String(error));
		process.exitCode = 1;
	});
}
